---
title: "Linear_Model"
author: "Judy Hua Zhu"
date: "2025-04-06"
output: html_document
---
Introduction and Clarification:
We are creating three linear models with different independent variable combinations:
Model 1: Technology + Class
Model 2: Technology + Net Capacity Factor
Model 3: Technology + Annual Energy Generation

All work are done collectively as a team.

```{r message=FALSE, warning=FALSE}
#Load packages
library(tidyverse)
library(here)
library(dplyr)
library(readxl)
library(openxlsx)

#Load in data
Solar_ATB <- read.csv("Processed_Data/Solar_ATB_Processed.csv")
```

```{r}
Model1.lm <- lm(LCOE ~
                Technology +
                Class,
                data = Solar_ATB)
summary(Model1.lm)
plot(Model1.lm)
```
```{r}
# Remove data point 28,29,30
Solar_ATB_Model1.2 <- Solar_ATB[-c(28,29,30),]
Model1.2.lm <- lm(LCOE ~
                Technology +
                Net_Cap_Factor,
             data = Solar_ATB_Model1.2)
summary(Model1.2.lm)
plot(Model1.2.lm)
AIC(Model1.2.lm)
```


```{r message=FALSE, warning=FALSE}
Model2.lm <- lm(LCOE ~
                Technology +
                Net_Cap_Factor,
             data = Solar_ATB)
summary(Model2.lm)
plot(Model2.lm)
```

```{r}
# Remove data point 1,29,30
Solar_ATB_Model2.2 <- Solar_ATB[-c(1,29,30),]
Model2.2.lm <- lm(LCOE ~
                Technology +
                Net_Cap_Factor,
             data = Solar_ATB_Model2.2)
summary(Model2.2.lm)
plot(Model2.2.lm)
AIC(Model2.2.lm)
```
```{r}
# Model variable: Technology and generation
Model3.lm <- lm(LCOE ~
                Technology +
                log(Annual_Energy_Production),
             data = Solar_ATB)
summary(Model3.lm)
plot(Model3.lm)
```
```{r}
# Remove data point 1,29,30
Solar_ATB_Model3.2 <- Solar_ATB[-c(1,29,30),]
Model3.2.lm <- lm(LCOE ~
                Technology +
                log(Annual_Energy_Production),
             data = Solar_ATB_Model3.2)
summary(Model3.2.lm)
plot(Model3.2.lm)
AIC(Model3.2.lm)
```


