---
title: "Linear Models"
author: "Asreeta Ushasri and Judy Hua Zhu"
date: "04-05-2025"
output: html_document
---

```{r message=FALSE, warning=FALSE}
#Load packages
library(tidyverse)
library(here)
library(dplyr)
library(readxl)
library(openxlsx)
library(cowplot)

#Load in data
Solar_ATB <- read.csv("Processed_Data/Solar_ATB_Long.csv")

view(Solar_ATB)
Solar_ATB <- Solar_ATB %>%
  select(-"X")

view(Solar_ATB)

```


```{r}
library(lme4)
library(nlme)


Solar_ATB

multi_model1 <- lme(LCOE ~ Annual_Generation_MWh + Technology,
                   random = ~1 | Class, data = Solar_ATB)

summary(multi_model1)



residuals <- plot(multi_model1)

normality <- qqnorm(multi_model1)

assumptions <- plot_grid(
  residuals,
                         normality,
                         ncols = 2,
                         rel_heights = c(2, 2))

draw_label("",
                                               size = 10, color = "black")
print(assumptions)

assumptions <- ggdraw(plot = assumptions) +
  labs(title = "Assessing LCOE Multilevel Model Fit",
       caption =
       "The Fitted Values graph depicts equal variance
       amongst residuals in the multilevel model.
       The model meets requirements for homoscedasticity.
       The QQ Plot indicates the residuals follow the
       theoretical normal curve quite closely (except for
       a slight curve at the far right values). This model
       therefore meets the assumption for normally
       distributed residuals."
)

assumptions <- ggdraw() +
  draw_text("Assessing LCOE Multilevel Model Fit", 
            size = 16, fontface = "bold", x = 0.5, y = 0.97, hjust = 0.5) +
  draw_plot(assumptions, y = 0.1, height = 0.8) +
  draw_text("The Fitted Values graph depicts equal variance amongst residuals
            in the multilevel model. The model meets requirements for homoscedasticity.
            The QQ Plot indicates the residuals follow the theoretical normal
            curve quite closely (except for a slight curve at the far right values).
            This model therefore meets the assumption for normally distributed residuals.", 
            size = 10, x = 0.5, y = 0.4, hjust = 0.5)

assumptions

save_plot("assumptions.png", assumptions, base_height = 7, base_width = 8)

AIC(multi_model1)
```


```{r}
# Graph multilevel model
library(broom.helpers)
tbl_regression(multi_model1)

multi_results <- tidy(multi_model1,
                         exponentiate = TRUE,
                         conf.int = TRUE)
```




```{r}
gen1.lm <- lm(LCOE ~
                Class + Technology +
                Annual_Generation_MWh,
             data = Solar_ATB)
```



```{r}
plot(gen1.lm)

```

```{r}

Solar_ATB_log <- Solar_ATB %>% 
  mutate(Annual_Energy_Production_log =
           log10(Annual_Energy_Production))

gen2.lm <- lm(LCOE ~
                Class + Technology +
                Annual_Energy_Production_log,
             data = Solar_ATB_log)

gen3.lm <- lm(LCOE ~
                Annual_Energy_Production + CAPEX,
             data = Solar_ATB)

gen4.lm <- lm(LCOE ~
                Annual_Energy_Production_log + Construct_Finance_Costs,
             data = Solar_ATB_log)


```


```{r}

plot(gen2.lm)
plot(gen3.lm)
plot(gen4.lm)

```

# Testing Net Capacity

```{r}
net1.lm <- lm(LCOE ~
                Net_Cap_Factor + Technology,
             data = Solar_ATB_log)

Solar_ATB_log <- Solar_ATB %>% 
  mutate(Net_Cap_Factor_log =
           log10(Net_Cap_Factor))

net2.lm <- lm(LCOE ~
                Net_Cap_Factor_log + Technology,
             data = Solar_ATB_log)

class.lm <- lm(LCOE ~
                Class + Technology,
             data = Solar_ATB_log)

plot(net1.lm)
plot(net2.lm)
plot(class.lm)

```

```{r}



summary(multi_model1)

multi_model2 <- lme(LCOE ~ Net_Cap_Factor +
                      Annual_Energy_Production + Technology,
                   random = ~1 | Class, data = Solar_ATB)

summary(multi_model2)

```

