---
title: "Evaluate variables"
output: html_document
---

```{r}
library(tidyverse)
library(dplyr)
library(here)
library(readxl)
#install.packages("openxlsx")
library(openxlsx)
library(plyr)
getwd()
```


```{r}
Processed_ATB <- read_csv("Solar_ATB_Processed.csv")
```
```{r}
# Delete the first two columns 
Processed_ATB <- Processed_ATB[,-1]
Processed_ATB <- Processed_ATB[,-1]
# Factorize technology
Processed_ATB$Technology = factor (Processed_ATB$Technology, 
                levels = c("Advanced","Moderate","Conservative"))
Processed_ATB$Class = factor (Processed_ATB$Class, 
                levels = c(1,2,3,4,5,6,7,8,9,10))
```

```{r}
# Visualization
# Use Rice Rule(2n^(1/3)) to determine bin size
2*30^(1/3) #6.21, Bin size = 6
ggplot(data = Processed_ATB, aes(x=Technology,y=LCOE,color=Technology))+
  geom_boxplot()+
  theme_bw()
# We can see Advanced technology has lowest LCOE, and conservative ones have higher LCOE
```
```{r}
ggplot(data = Processed_ATB, aes(y=LCOE, x= Class,color=Class))+
  geom_boxplot()+
  #facet_wrap(~Class)+
  theme_bw()
```


