---

title: "Data_Wrangling"
author: "Asreeta Ushasri"
date: "`r Sys.Date()`"
output: pdf_document

---

```{r message=FALSE, warning=FALSE}
#Set up

library(tidyverse)
#install.packages("dplyr")
#library(plyr)
library(dplyr)
library(here)
library(readxl)
#install.packages("openxlsx")
library(openxlsx)
library(tidyr)

getwd()

```



```{r}
#Import ATB data
#Solar PV excel sheet has many tables of data
#Need to import data as separate data frames into R
#Specify cell range using read_xlsx function
#Make sure to install read_xl package

Solar_ATB <- read.csv("2024_ATB.csv")
#view(Solar_ATB)

#Rename columns

Solar_ATB <- Solar_ATB %>% 
  rename(Class = `X.9`,
         Technology = `X.10`,
    Year_2022 = `https...atb.nrel.gov.electricity.2024.utility.scale_pv`,
    Year_2023 = `X.11`,
    Year_2024 = `X.12`,
    Year_2025 = `X.13`,
    Year_2026 = `X.14`)

#view(Solar_ATB)

#Need to remove symbols, spaces, etc.

Solar_ATB$Class <- gsub("%", "", Solar_ATB$Class)
Solar_ATB$Class <- gsub(",", "", Solar_ATB$Class)
Solar_ATB$Class <- gsub("\\$", "", Solar_ATB$Class)
Solar_ATB$Class <- gsub(" ", "_", Solar_ATB$Class)
Solar_ATB$Class <- gsub("-", "_", Solar_ATB$Class)
Solar_ATB$Technology <- gsub("%", "", Solar_ATB$Technology)
Solar_ATB$Technology <- gsub(",", "", Solar_ATB$Technology)
Solar_ATB$Technology <- gsub("\\$", "", Solar_ATB$Technology)
Solar_ATB$Technology <- gsub(" ", "_", Solar_ATB$Technology)
Solar_ATB$Technology <- gsub("-", "_", Solar_ATB$Technology)
Solar_ATB$Year_2022 <- gsub("%", "", Solar_ATB$Year_2022)
Solar_ATB$Year_2022 <- gsub(",", "", Solar_ATB$Year_2022)
Solar_ATB$Year_2022 <- gsub("\\$", "", Solar_ATB$Year_2022)
Solar_ATB$Year_2023 <- gsub("%", "", Solar_ATB$Year_2023)
Solar_ATB$Year_2023 <- gsub(",", "", Solar_ATB$Year_2023)
Solar_ATB$Year_2023 <- gsub("\\$", "", Solar_ATB$Year_2023)
Solar_ATB$Year_2024 <- gsub("%", "", Solar_ATB$Year_2024)
Solar_ATB$Year_2024 <- gsub(",", "", Solar_ATB$Year_2024)
Solar_ATB$Year_2024 <- gsub("\\$", "", Solar_ATB$Year_2024)
Solar_ATB$Year_2025 <- gsub("%", "", Solar_ATB$Year_2025)
Solar_ATB$Year_2025 <- gsub(",", "", Solar_ATB$Year_2025)
Solar_ATB$Year_2025 <- gsub("\\$", "", Solar_ATB$Year_2025)
Solar_ATB$Year_2026 <- gsub("%", "", Solar_ATB$Year_2026)
Solar_ATB$Year_2026 <- gsub(",", "", Solar_ATB$Year_2026)
Solar_ATB$Year_2026 <- gsub("\\$", "", Solar_ATB$Year_2026)

#Create separate DF for each variable

Assumptions <- Solar_ATB[51:81, 10:17]
Net_Cap_Factor <- Solar_ATB[86:116, 10:17]
Annual_Energy_Production <- Solar_ATB[118:148, 10:17]
CAPEX <- Solar_ATB[150:180, 10:17]
Construct_Finance_Costs <- Solar_ATB[182:212, 10:17]
Overnight_Cap_Costs <- Solar_ATB[214:244, 10:17]
Fixed_OM <- Solar_ATB[246:276, 10:17]
Variable_OM <- Solar_ATB[278:308, 10:17]
Grid_Connect_Cost <- Solar_ATB[313:343, 10:17]
LCOE <- Solar_ATB[346:376, 10:17]
Tax_Credit <- Solar_ATB[378:381, 10:17]

#view(LCOE)
```


# Create Pivot Tables

```{r}
Net_cap_long <- Net_Cap_Factor %>% 
  pivot_longer(cols = Year_2022:Year_2026,
               names_to = "Year",
               values_to = "Net_Capacity_Factor")

#view(Net_cap_long)

Annual_Energy_Long <- Annual_Energy_Production %>% 
  pivot_longer(cols = Year_2022:Year_2026,
               names_to = "Year",
               values_to = "Annual_Generation_MWh")

CAPEX_Long <- CAPEX %>% 
  pivot_longer(cols = Year_2022:Year_2026,
               names_to = "Year",
               values_to = "CAPEX")

CFC_Long <- Construct_Finance_Costs %>% 
  pivot_longer(cols = Year_2022:Year_2026,
               names_to = "Year",
               values_to = "Construction_Finance_Costs")

Overnight_Long <- Overnight_Cap_Costs %>% 
  pivot_longer(cols = Year_2022:Year_2026,
               names_to = "Year",
               values_to = "Overnight_Capital_Costs")

Fixed_OM_Long <- Fixed_OM %>% 
  pivot_longer(cols = Year_2022:Year_2026,
               names_to = "Year",
               values_to = "Fixed_OM_Costs")

#Variable O&M is zero for solar power
#no need to include in final data frame

Grid_Connect_Costs_Long <- Grid_Connect_Cost %>% 
  pivot_longer(cols = Year_2022:Year_2026,
               names_to = "Year",
               values_to = "Grid_Connection_Costs")

LCOE_Long <- LCOE %>% 
  pivot_longer(cols = Year_2022:Year_2026,
               names_to = "Year",
               values_to = "LCOE")


```

```{r}
#Combine data frames

view(Net_cap_long)
  

df_pivot <- list(Net_cap_long,
                             Annual_Energy_Long,
                             CAPEX_Long,
                             CFC_Long,
                             Overnight_Long,
                             Fixed_OM_Long,
                             Grid_Connect_Costs_Long,
                             LCOE_Long)

Solar_ATB_Long <- Net_cap_long %>%
  left_join(Annual_Energy_Long, by = c("Class", "Technology", "Year")) %>%
  left_join(CAPEX_Long, by = c("Class", "Technology", "Year")) %>%
  left_join(CFC_Long, by = c("Class", "Technology", "Year")) %>%
  left_join(Overnight_Long, by = c("Class", "Technology", "Year")) %>%
  left_join(Fixed_OM_Long, by = c("Class", "Technology", "Year")) %>%
  left_join(Grid_Connect_Costs_Long, by = c("Class", "Technology", "Year")) %>%
  left_join(LCOE_Long, by = c("Class", "Technology", "Year"))

#view(Solar_ATB_Long)
#Also clean up class name and year name

Solar_ATB_Long <- Solar_ATB_Long %>% 
  mutate(Class = factor(Class, levels = c("Utility_PV___Class_1",
                                          "Utility_PV___Class_2",
                                          "Utility_PV___Class_3",
                                          "Utility_PV___Class_4",
                                          "Utility_PV___Class_5",
                                          "Utility_PV___Class_6",
                                          "Utility_PV___Class_7",
                                          "Utility_PV___Class_8",
                                          "Utility_PV___Class_9",
                                          "Utility_PV___Class_10"),
                        labels = c(1, 2, 3, 4, 5, 6, 7, 8, 9, 10)))

#view(Solar_ATB_Long)
#Need to get rid of blank columns

Solar_ATB_Long <- Solar_ATB_Long %>%
  select(-"X.8.x") %>% 
  select(-"X.8.y") %>% 
  select(-"X.8.x.x") %>% 
  select(-"X.8.y.y") %>% 
  select(-"X.8.x.x.x") %>% 
  select(-"X.8.y.y.y") %>% 
  select(-"X.8.x.x.x.x") %>% 
  select(-"X.8.y.y.y.y")

#view(Solar_ATB_Long)

#Clean up year names
Solar_ATB_Long$Year <- gsub("Year_", "", Solar_ATB_Long$Year)
#Delete blank rows
Solar_ATB_Long <- Solar_ATB_Long[-c(151, 152, 153, 154, 155), ]

view(Solar_ATB_Long)


#Save data frame
write.csv(Solar_ATB_Long, "C:/Users/Ashree/OneDrive/Desktop/Spring_2025/Stats_Modeling/ENV_710/Processed_Data/Solar_ATB_Long.csv")

```


# Averages
These averages will be used in the initial data visualization

```{r}
#Create an average value for the five years

view(Net_Cap_Factor)

Net_Cap_Factor <- Net_Cap_Factor %>%
  mutate(Net_Cap_Factor = rowMeans(select(., Year_2022:Year_2026) %>% 
                             mutate(across(everything(), as.numeric)),
                            na.rm = TRUE))


Net_Cap_Factor_processed <- Net_Cap_Factor%>% 
  select(Class, Technology, Net_Cap_Factor)


#Process annual energy production
Annual_Energy_Production <- Annual_Energy_Production %>%
  mutate(Annual_Energy_Production =
           rowMeans(select(., Year_2022:Year_2026) %>% 
                             mutate(across(everything(), as.numeric)),
                            na.rm = TRUE))
Annual_Energy_Production_processed <- Annual_Energy_Production %>% 
  select(Class, Technology, Annual_Energy_Production)

#Next, process capex
CAPEX <- CAPEX %>%
  mutate(CAPEX =
           rowMeans(select(., Year_2022:Year_2026) %>% 
                             mutate(across(everything(), as.numeric)),
                            na.rm = TRUE))
CAPEX_processed <- CAPEX %>% 
  select(Class, Technology, CAPEX)

#Processing CFC next
Construct_Finance_Costs <- Construct_Finance_Costs %>%
  mutate(Construct_Finance_Costs =
           rowMeans(select(., Year_2022:Year_2026) %>% 
                             mutate(across(everything(), as.numeric)),
                            na.rm = TRUE))
Construct_Finance_Costs_processed <- Construct_Finance_Costs %>% 
  select(Class, Technology, Construct_Finance_Costs)

#Overnight Capacity Costs
Overnight_Cap_Costs <- Overnight_Cap_Costs %>%
  mutate(Overnight_Cap_Costs =
           rowMeans(select(., Year_2022:Year_2026) %>% 
                             mutate(across(everything(), as.numeric)),
                            na.rm = TRUE))
Overnight_Cap_Costs_processed <- Overnight_Cap_Costs %>% 
  select(Class, Technology, Overnight_Cap_Costs)

#FixedO&M
Fixed_OM <- Fixed_OM %>%
  mutate(Fixed_OM =
           rowMeans(select(., Year_2022:Year_2026) %>% 
                             mutate(across(everything(), as.numeric)),
                            na.rm = TRUE))
Fixed_OM_processed <- Fixed_OM %>% 
  select(Class, Technology, Fixed_OM)

#VariableO&M
Variable_OM <- Variable_OM %>%
  mutate(Variable_OM =
           rowMeans(select(., Year_2022:Year_2026) %>% 
                             mutate(across(everything(), as.numeric)),
                            na.rm = TRUE))
Variable_OM_processed <- Variable_OM %>% 
  select(Class, Technology, Variable_OM)

#GridCC
Grid_Connect_Cost <- Grid_Connect_Cost %>%
  mutate(Grid_Connect_Cost =
           rowMeans(select(., Year_2022:Year_2026) %>% 
                             mutate(across(everything(), as.numeric)),
                            na.rm = TRUE))
Grid_Connect_Cost_processed <- Grid_Connect_Cost %>% 
  select(Class, Technology, Grid_Connect_Cost)


#LCOE processing
LCOE <- LCOE %>%
  mutate(LCOE = rowMeans(select(., Year_2022:Year_2026) %>% 
                             mutate(across(everything(), as.numeric)),
                            na.rm = TRUE))

LCOE_processed <- LCOE %>% 
  select(Class, Technology, LCOE)

view(LCOE_processed)
view(LCOE)

```

# Summary Stats

```{r}
library(gt)


LCOE <- LCOE %>% 
  mutate(Class = factor(Class, levels = c("Utility_PV___Class_1",
                                          "Utility_PV___Class_2",
                                          "Utility_PV___Class_3",
                                          "Utility_PV___Class_4",
                                          "Utility_PV___Class_5",
                                          "Utility_PV___Class_6",
                                          "Utility_PV___Class_7",
                                          "Utility_PV___Class_8",
                                          "Utility_PV___Class_9",
                                          "Utility_PV___Class_10"),
                        labels = c(1, 2, 3, 4, 5, 6, 7, 8, 9, 10)))


Net_Cap_Factor <- Net_Cap_Factor %>% 
  mutate(Class = factor(Class, levels = c("Utility_PV___Class_1",
                                          "Utility_PV___Class_2",
                                          "Utility_PV___Class_3",
                                          "Utility_PV___Class_4",
                                          "Utility_PV___Class_5",
                                          "Utility_PV___Class_6",
                                          "Utility_PV___Class_7",
                                          "Utility_PV___Class_8",
                                          "Utility_PV___Class_9",
                                          "Utility_PV___Class_10"),
                        labels = c(1, 2, 3, 4, 5, 6, 7, 8, 9, 10)))

Annual_Energy_Production <- Annual_Energy_Production %>% 
  mutate(Class = factor(Class, levels = c("Utility_PV___Class_1",
                                          "Utility_PV___Class_2",
                                          "Utility_PV___Class_3",
                                          "Utility_PV___Class_4",
                                          "Utility_PV___Class_5",
                                          "Utility_PV___Class_6",
                                          "Utility_PV___Class_7",
                                          "Utility_PV___Class_8",
                                          "Utility_PV___Class_9",
                                          "Utility_PV___Class_10"),
                        labels = c(1, 2, 3, 4, 5, 6, 7, 8, 9, 10)))

#first make summary table of LCOE

view(LCOE)

LCOE <- LCOE[-31, ]

LCOE_sum <- LCOE %>%
  select(Class, Technology, Year_2022, Year_2023, Year_2024, Year_2025, Year_2026) %>%
  mutate(across(starts_with("Year"), as.numeric)) %>% 
  group_by(Class, Technology) %>%
  summarise(
    Min = min(c(Year_2022, Year_2023, Year_2024, Year_2025, Year_2026), na.rm = TRUE),
    Median = median(c(Year_2022, Year_2023, Year_2024, Year_2025, Year_2026), na.rm = TRUE),
    Max = max(c(Year_2022, Year_2023, Year_2024, Year_2025, Year_2026), na.rm = TRUE),
    Mean = mean(c(Year_2022, Year_2023, Year_2024, Year_2025, Year_2026), na.rm = TRUE),
    `Standard Deviation` = sd(c(Year_2022, Year_2023, Year_2024, Year_2025, Year_2026), na.rm = TRUE),
    Variance = var(c(Year_2022, Year_2023, Year_2024, Year_2025, Year_2026), na.rm = TRUE),
    .groups = "drop"
  )


LCOE_sum2 <- LCOE %>%
  select(Class, Technology, Year_2022, Year_2023, Year_2024, Year_2025, Year_2026) %>%
  mutate(across(starts_with("Year"), as.numeric)) %>%
  summarise(
    Min = min(c(Year_2022, Year_2023, Year_2024, Year_2025, Year_2026), na.rm = TRUE),
    Median = median(c(Year_2022, Year_2023, Year_2024, Year_2025, Year_2026), na.rm = TRUE),
    Max = max(c(Year_2022, Year_2023, Year_2024, Year_2025, Year_2026), na.rm = TRUE),
    Mean = mean(c(Year_2022, Year_2023, Year_2024, Year_2025, Year_2026), na.rm = TRUE),
    `Standard Deviation` = sd(c(Year_2022, Year_2023, Year_2024, Year_2025, Year_2026), na.rm = TRUE),
    Variance = var(c(Year_2022, Year_2023, Year_2024, Year_2025, Year_2026), na.rm = TRUE),
    .groups = "drop"
  )

# Use gt to format the table and add a title
LCOE_sum <- LCOE_sum %>% 
  gt() %>%
  tab_header(
    title = "U.S. Utility-Scale PV LCOE ($/MWh) by Class and Technology, 2022 - 2026",
    subtitle = "Number of Observations: Each year has 30 observations and 5 years are sampled (150 observations total in this table). The linear models were built based on the average values for categorical variables."
  )

gtsave(LCOE_sum, "LCOE_summary_table.html",
       path = here())


LCOE_sum2 <- LCOE_sum2 %>% 
  gt() %>%
  tab_header(
    title = "U.S. Utility-Scale PV LCOE ($/MWh) by Class and Technology, 2022 - 2026",
    subtitle = "Number of Observations: Each year has 30 observations and 5 years are sampled (150 observations total in this table). The linear models were built based on the average values for categorical variables."
  )

gtsave(LCOE_sum2, "LCOE_summary_table2.html",
       path = here())
```

```{r}

here()

#Now net capacity
Net_Cap_Factor <- Net_Cap_Factor[-31, ]

Net_Cap_Factor_sum <- Net_Cap_Factor %>%
  select(Class, Technology, Year_2022, Year_2023, Year_2024, Year_2025, Year_2026) %>%
  mutate(across(starts_with("Year"), as.numeric)) %>% 
  group_by(Class, Technology) %>%
  summarise(
    Min = min(c(Year_2022, Year_2023, Year_2024, Year_2025, Year_2026), na.rm = TRUE),
    Median = median(c(Year_2022, Year_2023, Year_2024, Year_2025, Year_2026), na.rm = TRUE),
    Max = max(c(Year_2022, Year_2023, Year_2024, Year_2025, Year_2026), na.rm = TRUE),
    Mean = mean(c(Year_2022, Year_2023, Year_2024, Year_2025, Year_2026), na.rm = TRUE),
    `Standard Deviation` = sd(c(Year_2022, Year_2023, Year_2024, Year_2025, Year_2026), na.rm = TRUE),
    Variance = var(c(Year_2022, Year_2023, Year_2024, Year_2025, Year_2026), na.rm = TRUE),
    .groups = "drop"
  )


# Use gt to format the table and add a title
Net_Cap_Factor_sum <- Net_Cap_Factor_sum %>% 
  gt() %>%
  tab_header(
    title = "U.S. Utility-Scale PV Net Capacity Factor (%) by Class and Technology, 2022 - 2026",
    subtitle = "Number of Observations: Each year has 30 observations and 5 years are sampled (150 observations total in this table). The linear models were built based on the average values for categorical variables."
  )

#Save summary stats
gtsave(Net_Cap_Factor_sum, "Net_Cap_Factor_summary_table.html",
       path = here())
```
```{r}
Net_Cap_Factor_sum2 <- Net_Cap_Factor %>%
  select(Class, Technology, Year_2022, Year_2023, Year_2024, Year_2025, Year_2026) %>%
  mutate(across(starts_with("Year"), as.numeric)) %>%
  summarise(
    Min = min(c(Year_2022, Year_2023, Year_2024, Year_2025, Year_2026), na.rm = TRUE),
    Median = median(c(Year_2022, Year_2023, Year_2024, Year_2025, Year_2026), na.rm = TRUE),
    Max = max(c(Year_2022, Year_2023, Year_2024, Year_2025, Year_2026), na.rm = TRUE),
    Mean = mean(c(Year_2022, Year_2023, Year_2024, Year_2025, Year_2026), na.rm = TRUE),
    `Standard Deviation` = sd(c(Year_2022, Year_2023, Year_2024, Year_2025, Year_2026), na.rm = TRUE),
    Variance = var(c(Year_2022, Year_2023, Year_2024, Year_2025, Year_2026), na.rm = TRUE),
    .groups = "drop"
  )


# Use gt to format the table and add a title
Net_Cap_Factor_sum2 <- Net_Cap_Factor_sum2 %>% 
  gt() %>%
  tab_header(
    title = "U.S. Utility-Scale PV Net Capacity Factor (%), 2022 - 2026",
    subtitle = "Number of Observations: Each year has 30 observations and 5 years are sampled (150 observations total in this table). The linear models were built based on the average values for categorical variables."
  )

#Save summary stats
gtsave(Net_Cap_Factor_sum2, "Net_Cap_Factor_summary_table2.html",
       path = here())
```





```{r}
#Next annual generation
Annual_Energy_Production <- Annual_Energy_Production[-31, ]

Annual_Energy_Production_sum <- Annual_Energy_Production %>%
  select(Class, Technology, Year_2022, Year_2023, Year_2024, Year_2025, Year_2026) %>%
  mutate(across(starts_with("Year"), as.numeric)) %>% 
  group_by(Class, Technology) %>%
  summarise(
    Min = min(c(Year_2022, Year_2023, Year_2024, Year_2025, Year_2026), na.rm = TRUE),
    Median = median(c(Year_2022, Year_2023, Year_2024, Year_2025, Year_2026), na.rm = TRUE),
    Max = max(c(Year_2022, Year_2023, Year_2024, Year_2025, Year_2026), na.rm = TRUE),
    Mean = mean(c(Year_2022, Year_2023, Year_2024, Year_2025, Year_2026), na.rm = TRUE),
    `Standard Deviation` = sd(c(Year_2022, Year_2023, Year_2024, Year_2025, Year_2026), na.rm = TRUE),
    Variance = var(c(Year_2022, Year_2023, Year_2024, Year_2025, Year_2026), na.rm = TRUE),
    .groups = "drop"
  )


# Use gt to format the table and add a title
Annual_Energy_Production_sum <- Annual_Energy_Production_sum %>% 
  gt() %>%
  tab_header(
    title = "U.S. Utility-Scale PV Annual Electricity Generation (MWh) by Class and Technology, 2022 - 2026",
    subtitle = "Number of Observations: Each year has 30 observations and 5 years are sampled (150 observations total in this table). The linear models were built based on the average values for categorical variables."
  )

#Save summary stats
gtsave(Annual_Energy_Production_sum, "Annual_Energy_summary_table.html",
       path = here())





```


```{r}
#Next annual generation

Annual_Energy_Production_sum2 <- Annual_Energy_Production %>%
  select(Class, Technology, Year_2022, Year_2023, Year_2024, Year_2025, Year_2026) %>%
  mutate(across(starts_with("Year"), as.numeric)) %>%
  summarise(
    Min = min(c(Year_2022, Year_2023, Year_2024, Year_2025, Year_2026), na.rm = TRUE),
    Median = median(c(Year_2022, Year_2023, Year_2024, Year_2025, Year_2026), na.rm = TRUE),
    Max = max(c(Year_2022, Year_2023, Year_2024, Year_2025, Year_2026), na.rm = TRUE),
    Mean = mean(c(Year_2022, Year_2023, Year_2024, Year_2025, Year_2026), na.rm = TRUE),
    `Standard Deviation` = sd(c(Year_2022, Year_2023, Year_2024, Year_2025, Year_2026), na.rm = TRUE),
    Variance = var(c(Year_2022, Year_2023, Year_2024, Year_2025, Year_2026), na.rm = TRUE),
    .groups = "drop"
  )


# Use gt to format the table and add a title
Annual_Energy_Production_sum2 <- Annual_Energy_Production_sum2 %>% 
  gt() %>%
  tab_header(
    title = "U.S. Utility-Scale PV Annual Electricity Generation (MWh), 2022 - 2026",
    subtitle = "Number of Observations: Each year has 30 observations and 5 years are sampled (150 observations total in this table). The linear models were built based on the average values for categorical variables."
  )

#Save summary stats
gtsave(Annual_Energy_Production_sum2, "Annual_Energy_summary_table2.html",
       path = here())
```


```{r}
#Save as images

library(webshot)

webshot::install_phantomjs()

webshot("LCOE_summary_table.html", "LCOE_summary_table.png")
webshot("Net_Cap_Factor_summary_table.html", "Net_Cap_Factor_summary_table.png")
webshot("Annual_Energy_summary_table.html", "Annual_Energy_summary_table.png")

webshot("LCOE_summary_table2.html", 
        "LCOE_summary_table2.png", 
        vwidth = 500,   # Set the width in pixels
        vheight = 250)

webshot("Net_Cap_Factor_summary_table2.html", 
        "NetCap2.png", 
        vwidth = 500,   # Set the width in pixels
        vheight = 250)

webshot("Annual_Energy_summary_table2.html", 
        "Annual_Energy_summary_table2.png", 
        vwidth = 500,   # Set the width in pixels
        vheight = 250)

```


```{r}
#Combine data frames
#view(Grid_Connect_Cost_processed)

dfs <- list(Net_Cap_Factor_processed,
                             Annual_Energy_Production_processed,
                             CAPEX_processed,
                             Construct_Finance_Costs_processed,
                             Overnight_Cap_Costs_processed,
                             Fixed_OM_processed,
                             Variable_OM_processed,
                             Grid_Connect_Cost_processed,
                             LCOE_processed)

Solar_ATB_Processed <- join_all(dfs,
                             by = c("Class", "Technology"),
                             type = "full")

Solar_ATB_Processed <- Solar_ATB_Processed %>% 
  mutate(Class = factor(Class, levels = c("Utility_PV___Class_1",
                                          "Utility_PV___Class_2",
                                          "Utility_PV___Class_3",
                                          "Utility_PV___Class_4",
                                          "Utility_PV___Class_5",
                                          "Utility_PV___Class_6",
                                          "Utility_PV___Class_7",
                                          "Utility_PV___Class_8",
                                          "Utility_PV___Class_9",
                                          "Utility_PV___Class_10"),
                        labels = c(1, 2, 3, 4, 5, 6, 7, 8, 9, 10)))


```



```{r}
#view(Solar_ATB_Processed)
#Remove the last row, blank/NA

Solar_ATB_Processed <- Solar_ATB_Processed[-31, ]

#view(Solar_ATB_Processed)
getwd()

#Save processed data in new folder

write.csv(Solar_ATB_Processed, "C:/Users/Ashree/OneDrive/Desktop/Spring_2025/Stats_Modeling/ENV_710/Processed_Data/Solar_ATB_Processed.csv")
```

